# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  #Der Webserver ist unter http://localhost:8080 erreichbar
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  #Falls dieser belegt ist, wird automatisch eine Alternative gewählt
  
  #die Dateien werden lokal im aktuellen Verzeichnis abgelegt:
  config.vm.synced_folder ".", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  
  #   # Customize the amount of memory on the VM:
  vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
	# Updates installieren
    apt-get update
	apt-get upgrade
	
	#Apache installieren
    apt-get install -y apache2
	
	#MySQL installieren
	debconf-set-selections <<< 'mysql-server mysql-server/root_password password vagrant'
	debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password vagrant'
	sudo apt-get install mysql-server -y
	
	#Firewall
	sudo apt-get install ufw
    sudo ufw status
	
	#Firewall Rules
	# Port 80 (HTTP) öffnen für alle
	sudo ufw allow 80/tcp
	
	sudo ufw -f enable
	# Port 22 (SSH) nur für den Host (wo die VM laufen) öffnen
	sudo ufw allow 22/tcp
	sudo ufw -f enable
	# Port 3306 (MySQL) nur für den web Server öffnen
	vagrant ssh database
	sudo ufw allow from localhost:3306 to any port 3306
	sudo ufw -f enable
   
	#Reverse Proxy Konfiguration
    sudo apt-get install libapache2-mod-proxy-html
	sudo apt-get install libxml2-dev -y
	sudo a2enmod proxy
	sudo a2enmod proxy_html
	sudo a2enmod proxy_http
	sudo service apache2 restart -y
	
	exit
  SHELL
end
